site_name: jet1090
site_description: High-performance ADS-B and Mode S decoding for real-time applications
repo_name: xoolive/rs1090
repo_url: https://github.com/xoolive/rs1090/
site_url: https://mode-s.org/jet1090/
nav:
  - Home: "index.md"
  - Installation: "install.md"
  - Sources of data: "sources.md"
  - Serving real-time data: "output.md"
  - Configuration options: "config.md"
  - Contribute to the project: "contribute.md"

theme:
  name: material
  logo: images/jet1090-logo.png
  favicon: images/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      baselevel: 1
